language: node_js
node_js:
  - "6.3.1"
sudo: false
before_script:
  - npm install
  - node phantomjs/server.js &
  - sleep 5
script:
  - rm -f data.lcov
  - phantomjs phantomjs/runner.js "http://localhost:8000/test/test.html?gruntReport&coverage"
  - node node_modules/coveralls/bin/coveralls.js < data.lcov
