# Site settings
title: jqTree
email: your-email@domain.com
description: "JqTree docs"
baseurl: "/jqTree"
url: "http://mbraak.github.io/jqTree/"

collections:
  entries:
    output: false
  examples:
    output: true

jqtree_version: 1.4.12

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["node_modules"]
